version: '3.9'

services:
  node_app:
    image: node:14
    container_name: node_app
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: bash -c "npm install && npm start"
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:latest
    container_name: chat-db
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: