version: '3.9'

services:
  node_app:
    image: node:14
    container_name: node_app
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
      - ./style.css:/app/style.css
    ports:
      - "3000:3000"
    command: bash -c "npm install && npm start"
    depends_on:
      - chat_db
    networks:
      - chat_network

  chat_db:
    image: mysql:5.7
    container_name: chat_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chat_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - chat_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: chat_db
      PMA_USER: root
      PMA_PASSWORD: password
    networks:
      - chat_network

volumes:
  mysql_data:

networks:
  chat_network:
