version: '3.9'

services:
  node_app:
    image: node:14
    container_name: node_app
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: bash -c "npm install && npm start"
    depends_on:
      - mongodb
    links:
      - mongodb:mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"